public with sharing class AuditproductItemsConstants {
    public static final String Approval_Status_Not_Submitted = UtilityClass.getOrgConstantValue('Approval_Status_Not_Submitted');
    public static final String Approval_Status_Pending = UtilityClass.getOrgConstantValue('Approval_Status_Pending');
    public static final String Audit_Records_Submitted_For_Approval = UtilityClass.getOrgConstantValue('Audit_Records_Submitted_For_Approval');
    public static final String Audit_Records_Submitted = UtilityClass.getOrgConstantValue('Audit_Records_Submitted');
}