/**
* @File Name : ContactSAPSyncBatchTest.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : April 7, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | April 7, 2025 |   | Initial Version
**/
@isTest
public class ContactSAPSyncBatchTest {

	       @isTest
    static void testConverage() {

         Test.startTest();
        ContactSAPSyncBatch.coveragemethod();
        Test.stopTest();

    }



}