/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-26-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class DummyClassTest {
	@isTest
    public static void runTest(){
        DummyClass.run();
    }
    @isTest
    public static void runTest2(){
        DummyClass2.run();
    }
    @isTest
    public static void runTest3(){
        DummyClass3.run();
    }
    @isTest
    public static void runTest4(){
        DummyClass4.run();
    }
    @isTest
    public static void runTest5(){
        DummyClass5.run();
    }
}