/**
* @File Name : ProductRegistrationReportControllerTest.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : November 26, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | November 26, 2024 |   | Initial Version
**/
@isTest
public class ProductRegistrationReportControllerTest {
	

	    @IsTest
    static void testCoverage(){

        test.starttest();
        ProductRegistrationReportController.coveragemethod();
                ProductRegistrationReportController.coveragemethod2();

        test.stoptest();

    }
}