global class SAPproductRegistrationAPIReqWrapper {

    public String Parameter;
    public String Brand;
    public String Model;
    public String SAP_External_Id;
    public String Parent_Product;
    public String Product_Family;
    public String Product_Family_Name;
    public String Product_Sub_Family;
    public String Product_Sub_Family_Name;
    public String Product_Type;
    public Decimal Capacity;
    public String Capacity_UOM;
    public String UOM;
    public String Manufacturer_Type;
    public String Manufacturer_No;
    public String Manufacturer_Name;
    public String Status;
    public Date Release_Date;
    public Boolean Is_Serialized;
    public Boolean Is_Installable;
    public Boolean Is_Obsolete;
    public Boolean Qualified_Revamp;
    public Integer Star_Rating;
    public String MR_Type;
    public Boolean Is_Field_Trial;
    public String Product_Category;
    public String Type;    
}